//login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//signup
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//authenticate
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

//create classroom
export const CREATE_CLASS_START = 'CREATE_CLASS_START';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_FAILURE = 'CREATE_CLASS_FAILURE';
export const CLEAR_CLASS_CODE = 'CLEAR_CLASS_CODE';

//join classroom 
export const JOIN_CLASSROOM ='JOIN_CLASSROOM'
//fetch classroom details
export const FECTH_CURRENT_CLASSROOM_DETAILS = 'FECTH_CURRENT_CLASSROOM_DETAILS'
export const CLEAR_CURRENT_CLASSROOM_DETAILS='CLEAR_CURRENT_CLASSROOM_DETAILS'

export const FETCH_UNREAD_MESSAGE_COUNT='FETCH_UNREAD_MESSAGE_COUNT'

//fetch user details
export const FETCH_USER_CLASS_DETAILS = 'FETCH_USER_CLASS_DETAILS'

//clear user class details
export const CLEAR_USER_CLASS_DETAILS='CLEAR_USER_CLASS_DETAILS'

//theme
export const SWITCH_THEME = 'SWITCH_THEME'

//to fetch lab details
export const FETCH_LAB_DETAILS = 'FETCH_LAB_DETAILS'
export const CLEAR_LAB_DETAILS = 'CLEAR_LAB_DETAILS'
//to create new code editor
export const CREATE_CODE_EDITOR = 'CREATE_CODE_EDITOR'

//posts
export const UPDATE_POSTS = 'UPDATE_POSTS';
//add posts
export const ADD_POST = 'ADD_POST';

//ADD COMMENT
export const ADD_COMMENT = 'ADD_COMMENT';

//liking a post
export const UPDATE_POST_LIKE = 'UPDATE_POST_LIKE';

//liking a comment
export const UPDATE_COMMENT_LIKE = 'UPDATE_COMMENT_LIKE';

//receiving earlier messages
export const GET_EARLIER_MESSAGES = 'GET_EARLIER_MESSAGES';
export const CLEAR_EARLIER_MESSAGES = 'CLEAR_EARLIER_MESSAGES';
export const UPDATE_CHAT_MESSAGE ='UPDATE_CHAT_MESSAGE';

// code execution
export const EXECUTION_START = 'EXECUTION_START';
export const EXECUTION_SUCCESS = 'EXECUTION_SUCCESS';
export const EXECUTION_FAILED = 'EXECUTION_FAILURE';
export const EXECUTION_CLEAR_STATE = 'EXECUTION_CLEAR_STATE';

// select language
export const SELECT_LANGUAGE = "SELECT_LANGUAGE";

//Quiz
export const QUIZ_CREATE_START = 'QUIZ_CREATE_START';
export const QUIZ_CREATE_SUCCESS = 'QUIZ_CREATE_SUCCESS';
export const QUIZ_CREATE_FAILED = 'QUIZ_CREATE_FAILURE';
export const QUIZ_CREATE_CLEAR_STATE = 'QUIZ_CREATE_CLEAR_STATE';
export const QUIZ_FETCH_ALL_SUCCESS ='QUIZ_FETCH_ALL_SUCCESS';
export const QUIZ_FETCH_SUCCESS = 'QUIZ_FETCH_SUCCESS';
export const QUIZ_SUBMIT_SUCCESS = 'QUIZ_SUBMIT_SUCCESS';
export const QUIZ_CLEAR = 'QUIZ_CLEAR';

